### PR TITLE
Add CI build with jobs

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
PR that adds CI-builds to the delivery repo

**How to test: **
- [ ] merge travis config into master
- [ ] make sure travis is enabled for this repo

**Expected outcome: **
- [ ] Master builds on travis 
- [ ] Screenshot

- [x] Reviewed @ingkebil 
- [ ] Tested
- [x] merge & deploy OK @ingkebil 

This is a minor bump since we add CI func but we don't add any end user func

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
@ingkebil can we merge this? I don't see how we can easily test it without getting the travis config into master?

**Comment by ingkebil** [comment]
Approved

**Comment by patrikgrenfeldt** [comment]
We will merge this, make sure it is ok and roll-back if it is not tested ok

**Comment by patrikgrenfeldt** [comment]
Test result:
image
The build config is processed and the build starts
👍

**Pull request merged**
